name: Chrysalis
favicon: null
layout_spectrum: 0.9827264319173992
typography_spectrum: 0.4747431646101177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6783151242416352
  lightness: 0.13580198516137898
  saturation: 0.4436161923222244
  rhythmicContrast: 0.20874977484345436
purpose: []
